### ISSUE TITLE
animated setting not disabled

### ISSUE THREAD

**Issue by larryhengl** [javisperez/tailwindcontentplaceholder#2]
hi, i'm trying out this plugin using svelte.  thanks for releasing it.
i configured it for no animation in tailwind.config.js:
```
...
animated: false,
...
```
i am getting the lines, but still seeing pulsing.  the lines should just be solid if no animation, right?

**Comment by javisperez** [comment]
oh, that sounds like a bug, thanks for opening an issue, will have a look asap, should be pretty easy to fix.

**Comment by javisperez** [comment]
@larryhengl i cant reproduce, can you please share a bit more of your tailwind config? where are you adding that flag? inside each placeholder or outside? it is working fine for me with:
```
  plugins: [
    require('./index')({
      animated: false,
      placeholders: {
         ...
```

**Comment by larryhengl** [comment]
@javisperez here's the snippet from the plugins array in my config file:
```js
require('tailwind-content-placeholder')({
      width: "80%",
      height: "100%",
      animated: false,
      placeholders: {
        'paragraph': {
          rows: [ // This class will have 4 rows:
            [100], // A 100% width row
            [100], // Another 100% width row
            [40], // A 40% width row
            [] // And an empty row, to create separation
          ]
        },
        'bullet': {
          rows: [
            [20, 80]
          ]
        }
      }
    }),
```
Using Chrome v88 on Mac.  Tailwind 2.0.2.

The two placeholder templates look like this (at different parts of the page):
```html
<div class="w-full h-full cp-paragraph"></div>
<div class="w-full h-full cp-bullet"></div>
```
The paragraph appears with pulsing, and the bullet is not rendered (even tried with dummy text in the div).

The generated CSS .cp-paragraph looks like this:
```css
.cp-paragraph::before {
    content: " ";
    height: 4em;
    color: transparent;
    width: 80%;
    display: block;
    background-position: 0 0;
    background-repeat: no-repeat;
    border-radius: 4px;
    /* -webkit-animation: contentPlaceholder 1.4s ease infinite; */
    animation: contentPlaceholder 1.4s ease infinite;
    background-image: url(data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100%' height='100%'><rect x='0%' y='0em' width='100%' height='calc(1em - 3px)' rx='4' fill='rgba(0, 0, 0, 0.1)' />,<rect x='0%' y='1em' width='100%' height='calc(1em - 3px)' rx='4' fill='rgba(0, 0, 0, 0.1)' />,<rect x='0%' y='2em' width='40%' height='calc(1em - 3px)' rx='4' fill='rgba(0, 0, 0, 0.1)' />,</svg>);
}
```
